root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./imageproxy"
  cmd = "go build willnorris.com/go/imageproxy/cmd/imageproxy"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".vscode", "docs", "etc", "internal", ".lh", ".github", "third_party"]
  exclude_file = ["LICENSE", "README.md", "imageproxy", ".golangci.yml", ".gitlab-ci.yml", ".gitignore", ".air.toml"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
